image: python:latest
variables:
    INDEX: nerim
stages:
    - quality
    - test
    - test-collection
    - build
    - publish
quality:
    stage: quality
    script:
        - pip install -r requirements.d/jenkins.txt
        - flake8 --output-file=./flake8.log
    artifacts:
        when: always
        paths:
            - ./flake8.log
test-collection:
    stage: test-collection
    artifacts:
        when: always
        paths:
            - ./unit-*.tests.xml
.test: &base_test
    stage: test
    script:
        - pip install "django>=${DJANGO_VERSION}.0,<${DJANGO_VERSION}.9999"
        - pip install -r requirements.d/tests.txt
        - pytest "--junitxml=./unit-${CI_JOB_NAME}.tests.xml"
.test27: &test27
    <<: *base_test
    image: python:2.7-alpine
.test34: &test34
    <<: *base_test
    image: python:3.4-alpine
.test35: &test35
    <<: *base_test
    image: python:3.5-alpine
.test36: &test36
    <<: *base_test
    image: python:3.6-alpine
test:python2:django18:
    <<: *test27
    variables:
        DJANGO_VERSION: '1.8'
test:python2:django19:
    <<: *test27
    variables:
        DJANGO_VERSION: '1.9'
test:python2:django110:
    <<: *test27
    variables:
        DJANGO_VERSION: '1.10'
test:python2:django111:
    <<: *test27
    variables:
        DJANGO_VERSION: '1.11'
test:python3:django18:
    <<: *test34
    variables:
        DJANGO_VERSION: '1.8'
test:python3:django19:
    <<: *test34
    variables:
        DJANGO_VERSION: '1.9'
test:python3:django110:
    <<: *test34
    variables:
        DJANGO_VERSION: '1.10'
test:python3:django111:
    <<: *test34
    variables:
        DJANGO_VERSION: '1.11'
test:python3:django20:
    <<: *test34
    variables:
        DJANGO_VERSION: '2.0'
test:python35:django18:
    <<: *test35
    variables:
        DJANGO_VERSION: '1.8'
test:python36:django18:
    <<: *test36
    variables:
        DJANGO_VERSION: '1.8'
build:
    stage: build
    script: python setup.py bdist_wheel
    artifacts:
        paths:
            - dist/*.whl
publish:
    stage: publish
    only:
        - releases
    script:
        - python setup.py register -r $INDEX
        - python setup.py bdist_wheel upload
